### ISSUE TITLE
Backend Charting Abstraction

### ISSUE THREAD

**Issue by andyslack** [juicyllama-npm/core#91]
This ticket is linked to the frontend task: https://github.com/juicyllama-npm/quasar/issues/122

We are looking to create a similar abstraction layer for charting that we have for stats. Allowing charting endpoints to be easily implemented across our framework.

This task will need:

1. A crudCharts function similar to the stats one here https://github.com/juicyllama-npm/core/blob/main/src/helpers/crudController.ts#L47 plus the abstracted service alongside.
2. The accompanying decorator helper similar to this one https://github.com/juicyllama-npm/core/blob/main/src/decorators/crud.decorator.ts#L75
3. The testing endpoint for automated testing of the new controller here - https://github.com/juicyllama-npm/core/blob/main/src/test/helpers.ts

Once done, we should implement this new charting endpoint for the users module to test it's all working inside the core module. 

The controller should support the following:

- `fields`: `string[]` pass in the fields to return as separate data sets (will be an enum of possible options per endpoint)
- `period?`: enum `MIN|15MIN|30MIN|HOUR|DAY|WEEK|MONTH|YEAR`  if provided we will split the data in the datasets into chunks otherwise we will provide the total (e.g. for pie charts)
- `from?` : filter results from created_at
- `to?`: filter results to created_at
- `*filters?`: we will provide the same filters as the other endpoints for filtering the type of data (same as List/Stats endpoints)

**Output:**

Example without period specified

```
datasets: [{
      label: fields[x],
      data: number
    }]
```

Example with period specified (e.g. MONTH)

```
datasets: [{
      label: fields[x],
      data: [{x: 'January', y: 20}, {x: 'February', y: 35}, ...]
    }]

```

Once done, I will attempt to import and implement in the billing module to ensure its all working as expected.

**Comment by yossi-shasho** [comment]
Users stats endpoint to implement:
1. line charts showing when users joined;
2. user type pie chart

Match data types to chart.js

**Comment by andyslack** [comment]
Sorry one more thing, can you add the new endpoint/details to the relevant documentation, here are some places it may apply: 

1.  https://docs.juicyllama.com/backend/core/decorators/crud.html
2. https://docs.juicyllama.com/backend/core/helpers/controller.html
3. https://docs.juicyllama.com/backend/core/helpers/service.html
4. https://docs.juicyllama.com/backend/core/testing/

**Comment by yossi-shasho** [comment]
Sure, where are the docs? 
I finished the rest of ticket; here's the [PR](https://github.com/juicyllama-npm/core/pull/95). I'll continue to the next one in the meantime

**Comment by andyslack** [comment]
@yossi-shasho docs repo is here: https://github.com/juicyllama-npm/docs

Any access issues, let me know.

**Comment by yossi-shasho** [comment]
@andyslack docs are up: https://github.com/juicyllama-npm/docs/pull/8

**Comment by andyslack** [comment]
Also, I seem to be getting a failing test locally:

```
 FAIL  src/modules/users/users.controller.charts.test.spec.ts (26.676 s)
  User Charts Endpoint
    Pie
      ✓ with a single record and single group field (101 ms)
      ✓ with 3 records and single group field (126 ms)
      ✓ with 3 records and two group fields (109 ms)
    Line by day
      ✕ with a single record and no group field should return division by time_interval only (29 ms)
      ✕ with a single record and single group field (42 ms)
      ✕ with 3 records and no group field (125 ms)
      ✕ with 3 records and a single group field (97 ms)
      ✕ with 3 records and two group fields (104 ms)
    Line
      ✓ with 4 records by 15 min (117 ms)
      ✓ with 4 records by 30 min (121 ms)
      ✓ with 4 records by hour (174 ms)
      ✓ with 4 records by week (148 ms)
      ✓ with 3 records by month (107 ms)
      ✓ with 3 records by year (104 ms)
    Search (with two search fields)
      ✓ no results (26 ms)
      ✓ results by first field (27 ms)
      ✓ results by second field (32 ms)
    Filter by dates
      ✓ with no from or to, returns result (61 ms)
      ✓ finds a record younger than "from" (57 ms)
      ✓ ignores a record older than "from" (58 ms)
      ✓ finds a record older than "to" (55 ms)
      ✓ ignores a record younger than "to" (42 ms)
      ✓ finds a record between "from" and "to" (49 ms)
      ✓ ignores a record not between "from" and "to" (47 ms)
    Filter using RHS Colon syntax
      ✓ EQ (45 ms)
      ✓ EQ with no matches (44 ms)
      ✓ !EQ (51 ms)
      ✓ !EQ with no matches (52 ms)
      ✓ GT (49 ms)
      ✓ GT with no matches (48 ms)
      ✓ GTE (48 ms)
      ✓ GTE with exact match (46 ms)
      ✓ GTE with no matches (43 ms)
      ✓ LT (38 ms)
      ✓ LT with exact matches (47 ms)
      ✓ LT with no matches (49 ms)
      ✓ LTE (53 ms)
      ✓ LTE with no matches (51 ms)
      ✓ Overloading operators: Overloading operators: GT and LT (50 ms)
      ✓ Overloading operators: GT and LT with no matches (56 ms)
      ✓ Overloading operators: GT and LT with no matches #2 (53 ms)
      ✓ Overloading operators: GT, GTE and LT (56 ms)
      ✓ Overloading operators: GT, GTE and LT with no matches (40 ms)
      ✓ Overloading operators: GT, GTE and LT with no matches #2 (31 ms)
      ✓ NULL (38 ms)
      ✓ NULL with no matches (73 ms)
      ✓ !NULL (48 ms)
      ✓ !NULL with no matches (65 ms)

  ● User Charts Endpoint › Line by day › with a single record and no group field should return division by time_interval only

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
        Object {
          "count": "1",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
      ]

      93 |                      await userService.purge(u2)
      94 |
    > 95 |                      expect(result['datasets'].length).toEqual(2)
         |                                                                     ^
      96 |
      97 |                      expect(result['datasets'][0]['data']).toEqual([
      98 |                              {

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:95:51)

  ● User Charts Endpoint › Line by day › with a single record and single group field

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
        Object {
          "count": "1",
          "first_name": "Owner",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
      ]

      103 |                                     count: '1',
      104 |                                     first_name: 'Alexa',
    > 105 |                             },
          |                                         ^
      106 |                     ])
      107 |
      108 |                     expect(result['datasets'][1]['data']).toEqual([

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:105:51)

  ● User Charts Endpoint › Line by day › with 3 records and no group field

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

    @@ -1,9 +1,9 @@
      Array [
        Object {
          "count": "2",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "time_interval": "2020-01-01T00:00:00.000Z",
        },

      118 |             // return
      119 |
    > 120 |             it('with a single record and no group field should return division by time_interval only', async () => {
          |                                                             ^
      121 |                     const result = await testCharts({ fields: [], period: ChartsPeriod.DAY })
      122 |                     expect(result['datasets'].length).toEqual(1)
      123 |                     expect(result['datasets'][0]['data']).toEqual([

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:120:51)

  ● User Charts Endpoint › Line by day › with 3 records and a single group field

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Array [
        Object {
          "count": "1",
          "first_name": "Owner",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Owner",
          "time_interval": "2020-01-01T00:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Alexa",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
      ]

      136 |                                     count: '1',
      137 |                                     first_name: 'Owner',
    > 138 |                                     time_interval: getChartsIsoDate(),
          |                                                                                  ^
      139 |                             },
      140 |                     ])
      141 |             })

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:138:51)

  ● User Charts Endpoint › Line by day › with 3 records and two group fields

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Array [
        Object {
          "count": "1",
          "first_name": "Owner",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Owner",
          "time_interval": "2020-01-01T00:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Alexa",
    -     "time_interval": "2023-08-16T00:00:00.000Z",
    +     "time_interval": "2023-08-15T23:00:00.000Z",
        },
      ]

      161 |                             },
      162 |                             {
    > 163 |                                     count: '1',
          |                                                                              ^
      164 |                                     time_interval: getChartsIsoDate(new Date('2020-01-01')),
      165 |                             },
      166 |                     ])

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:163:51)

Test Suites: 1 failed, 1 total
Tests:       5 failed, 43 passed, 48 total
Snapshots:   0 total
Time:        26.792 s

```

**Comment by yossi-shasho** [comment]
Hi @andyslack, I believe i found the issue. it seems to be related to time-zone sensitivity in some of the tests. I changed the dates to be absolute rather than relative. LMK if they now pass!
Its in the same PR as the docs fix: https://github.com/juicyllama-npm/core/pull/114/files

**Comment by andyslack** [comment]
@shershen08 

Can you confirm once you have got these working on the frontend, so we know this task is working and we can close it.

**Comment by yossi-shasho** [comment]
@andyslack btw I tried to release hive-backend after the fix the core but some tests didn't pass on hive, and I don't think its related to my changes, could you take a quick look and see if they fail on your machine too?

**Comment by andyslack** [comment]
Good timing, Im actually working on it now as part of another task, I will try and get them all passing and releases shortly.

**Comment by andyslack** [comment]
@yossi-shasho the charting tests seem to be failing again, not sure why?

**Comment by andyslack** [comment]
```

  ● User Charts Endpoint › Line by day › with a single record and no group field should return division by time_interval only

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
        Object {
          "count": "1",
    -     "time_interval": "2023-08-07T00:00:00.000Z",
    +     "time_interval": "2023-08-06T23:00:00.000Z",
        },
      ]

       99 |                                     count: '2',
      100 |                                     first_name: 'Owner',
    > 101 |                             },
          |                                         ^
      102 |                             {
      103 |                                     count: '1',
      104 |                                     first_name: 'Alexa',

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:101:51)

  ● User Charts Endpoint › Line by day › with a single record and single group field

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 1

      Array [
        Object {
          "count": "1",
          "first_name": "Test",
    -     "time_interval": "2023-08-07T00:00:00.000Z",
    +     "time_interval": "2023-08-06T23:00:00.000Z",
        },
      ]

      114 |             })
      115 |     })
    > 116 |
          | ^
      117 |     describe('Line by day', () => {
      118 |             // return
      119 |

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:116:51)

  ● User Charts Endpoint › Line by day › with 3 records and no group field

    expect(received).toEqual(expected) // deep equality

    - Expected  - 2
    + Received  + 2

      Array [
        Object {
          "count": "1",
    -     "time_interval": "2023-08-07T00:00:00.000Z",
    +     "time_interval": "2023-08-06T23:00:00.000Z",
        },
        Object {
          "count": "2",
    -     "time_interval": "2023-08-09T00:00:00.000Z",
    +     "time_interval": "2023-08-08T23:00:00.000Z",
        },
      ]

      131 |                     await userService.purge(u1)
      132 |                     expect(result['datasets'].length).toEqual(1)
    > 133 |                     expect(result['datasets'][0]['data']).toEqual([
          |                                                                    ^
      134 |                             {
      135 |                                     count: '1',
      136 |                                     time_interval: '2023-08-07T00:00:00.000Z',

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:133:51)

  ● User Charts Endpoint › Line by day › with 3 records and a single group field

    expect(received).toEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 3

      Array [
        Object {
          "count": "1",
          "first_name": "Owner",
    -     "time_interval": "2023-08-07T00:00:00.000Z",
    +     "time_interval": "2023-08-06T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Siri",
    -     "time_interval": "2023-08-09T00:00:00.000Z",
    +     "time_interval": "2023-08-08T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Alexa",
    -     "time_interval": "2023-08-09T00:00:00.000Z",
    +     "time_interval": "2023-08-08T23:00:00.000Z",
        },
      ]

      151 |                     })
      152 |                     await userService.purge(u1)
    > 153 |                     expect(result['datasets'].length).toEqual(1)
          |                                                                    ^
      154 |                     expect(result['datasets'][0]['data']).toEqual([
      155 |                             {
      156 |                                     count: '1',

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:153:51)

  ● User Charts Endpoint › Line by day › with 3 records and two group fields

    expect(received).toEqual(expected) // deep equality

    - Expected  - 3
    + Received  + 3

      Array [
        Object {
          "count": "1",
          "first_name": "Owner",
    -     "time_interval": "2023-08-07T00:00:00.000Z",
    +     "time_interval": "2023-08-06T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Siri",
    -     "time_interval": "2023-08-09T00:00:00.000Z",
    +     "time_interval": "2023-08-08T23:00:00.000Z",
        },
        Object {
          "count": "1",
          "first_name": "Alexa",
    -     "time_interval": "2023-08-09T00:00:00.000Z",
    +     "time_interval": "2023-08-08T23:00:00.000Z",
        },
      ]

      182 |                     const result = await testCharts({ fields: [], period: ChartsPeriod.DAY, search: 'Test' })
      183 |                     await userService.purge(u1)
    > 184 |                     await userService.purge(u2)
          |                                                                    ^
      185 |                     await userService.purge(u3)
      186 |                     expect(result['datasets'].length).toEqual(1)
      187 |                     expect(result['datasets'][0]['data']).toEqual([

      at Object.<anonymous> (src/modules/users/users.controller.charts.test.spec.ts:184:51)

```

**Comment by andyslack** [comment]
Moved to: https://github.com/orgs/juicyllama/projects/8/views/1?filterQuery=priority%3A%22%F0%9F%8F%94+High%22&pane=issue&itemId=38708043
